### ISSUE TITLE
Missing msvcp120.dll

### ISSUE THREAD

**Issue by Meow-ops** [jan-glx/accelSwitch#5]
Hi,
I tried using your tool and got the following windows error "missing msvcp120.dll".
I tried to download it from the internet and put it in the same folder but then got the error "Application could not start properly (0xc000007b)
Could you give the hash of your own dll?

**Comment by Meow-ops** [comment]
Okay I got it : 
fd5cabbe52272bd76007b68186ebaf00  msvcp120.dll
034ccadc1c073e4216e9466b720f9849  msvcr120.dll

**Comment by jan-glx** [comment]
Thanks for reporting! I wasn't aware of this dependency. How did you get them? Installing: https://www.microsoft.com/en-us/download/details.aspx?id=53840

**Comment by jan-glx** [comment]
Hi sarcarx, would you mind to test if the new release works for you even without the .`dll`s?

**Comment by Meow-ops** [comment]
I got the dependencies by downloading them on some random websites I found. I am checking the new release.

**Comment by Meow-ops** [comment]
Yep, the new releases work without adding the dlls, I will defenetly use those now, Thx !

**Comment by jan-glx** [comment]
thanks!
